wdr_lookfront:
    resource: "@WdrLookfrontBundle/Resources/config/routing.yml"
    prefix:   /

wdr_lookadmin:
    resource: "@WdrLookadminBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"